<?php
function get_data_excel()
{
  $arr = [
    "cargo" => [
      "Gobernador",
      "Gobernador",
      "Gobernador",
      "Gobernador",
      "Alcalde",
      "Alcalde",
      "Alcalde",
      "Concejal Lista",
      "Concejal Lista",
      "Concejal Lista",
      "Concejal Lista",
      "Concejal Lista",
      "Concejal Lista",
      "Concejal Lista",
      "Concejal Lista",
      "Concejal Lista",
      "Concejal Lista",
      "Concejal Nominal Circuito 1",
      "Concejal Nominal Circuito 1",
      "Concejal Nominal Circuito 1",
      "Concejal Nominal Circuito 2",
      "Concejal Nominal Circuito 2",
      "Concejal Nominal Circuito 2",
      "Concejal Nominal Circuito 2",
      "Concejal Nominal Circuito 2",
      "Concejal Nominal Circuito 2",
      "Concejal Nominal Circuito 2",
      "Concejal Nominal Circuito 2",
      "Concejal Nominal Circuito 2",
      "Concejal Nominal Circuito 2",
    ],
    "partido" => [
      "PSUV",
      "MUD",
      "",
      "OTROS",
      "PSUV",
      "MUD",
      "OTROS",
      "PSUV",
      "PSUV",
      "PSUV",
      "PSUV",
      "PSUV",
      "MUD",
      "AD/COPEI",
      "PCV",
      "MAS",
      "OTROS",
      "PSUV",
      "MUD",
      "OTROS",
      "PSUV",
      "PSUV",
      "PSUV",
      "MUD",
      "",
      "",
      "OTROS",
      "",
      "",
      "OTROS",
    ],
    "nombre_y_apellido" => [
      "HECTOR RODRIGUEZ",
      "DAVID UZCATEGUI",
      "CARLOS OCARIZ",
      "OTROS",
      "JOSE VICENTE RANGEL AVALOS",
      "ANDRES SCHLOETER",
      "OTROS",
      "APARICIO MARCANO ABRAHAM DAVID",
      "LARA DIOGENES ",
      "ARBOLEDA ALCON GLADYS",
      "ZERPA SERRANO JESUS",
      "RUIZ FUENTES EVELYN",
      "RADA ANGULO TADEO JOSE",
      " ROSALES RODRIGO ANTONIO",
      "MERIDA FUENTES RAFAEL ANGEL",
      "GUEVARA FRANCISCO JOSE",
      "OTROS",
      "CASTILLO JHONATHAN ENRIQUE",
      "MARRERO VELIZ ROXANA MARIBEL",
      "OTROS",
      "CHARRIS SANCHEZ RICHARD EDUARDO",
      "JIMENEZ CAMPOS YAZMIN JOSEFINA",
      " COLLANTES MARIA DOLORES",
      "MUD-JONATHAN MARTINEZ ",
      "NORIS CENTENO",
      "WILMAN VILLEGAS",
      "OTROS",
      "PEDROZA BANDRES ZULIMAR COROMOTO",
      "VIDAL SERODIO JUAN CARLOS",
      "OTROS",
    ]
  ];

  $new_arr = [];

  foreach ($arr["cargo"] as $i => $value) {
    $new_arr[$i]["cargo"] = $value;
    $new_arr[$i]["partido"] = $arr["partido"][$i];
    $new_arr[$i]["nombre_y_apellido"] = $arr["nombre_y_apellido"][$i];
  }

  return $new_arr;
}
